### ISSUE TITLE
repos.php.earth not accessible

### ISSUE THREAD

**Issue by nabilfrancis** [phpearth/PHP.earth#38]
Hi team,

It seems that repos.php.earth is not accessible.
This is causing a number of our docker builds to fail.
Can you please have a look?

Thanks,
Nabil

**Comment by Maikuolan** [comment]
@petk

**Comment by nabilfrancis** [comment]
We are also getting an SSL certificate error when accessing https://status.php.earth/. Not sure if this is related.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/20302614/169952507-053d8076-10b1-436c-9944-ed04d4d391fa.png">

**Comment by Maikuolan** [comment]
Speculating, but I don't think it's related, but rather an additional, separate issue. Pinging the subdomain in question (repos.php.earth) results in lost packets, suggesting either that there's no longer an NS record registered for the subdomain in question or that something else has gone wrong, e.g., with routing. But, I'm not the expert on that matter, seeing as I don't handle the domains for php.earth, and I might be wrong (but @petk should know a little more, which is why I tagged him here).

**Comment by nabilfrancis** [comment]
Thanks, for the update, Caleb
We are hoping for this to be resolved soon :)

**Comment by manuellemos** [comment]
It seems the data center connectivity is not working.

You can check this site:

https://downforeveryoneorjustme.com/repos.php.earth?proto=http

**Comment by manuellemos** [comment]
May it is time to check with the hosting company to asking what is going on.

**Comment by petk** [comment]
Hello, repos.php.earth haven't been maintained for a long time now and I've shut them down. You'll need to migrate to Alpine official upstream repositories instead. Thanks.
